name: Fetch Discovery files
on:
  schedule:
    - cron: 0 5 * * 5
  workflow_dispatch:

jobs:
  fetch:
    name: Fetch
    runs-on:  [ubuntu-latest]
    timeout-minutes: 60
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Setup Java (temurin@21)
        id: setup-java-temurin-21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: discovery fetch
        run: sbt discoveryFetch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            **/discovery.json
          commit-message: "Updated discovery files"
          author: Erlend Hamnaberg<erlend@hamnaberg.net>
          body: Updated discovery files
          title: 'Discovery files by create-pull-request action'